name: Build Kernel using yaap Source

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      KERNEL_WORKSPACE: "/mnt/kernel_workspace"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set Swap
        run: |
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm -rf $SWAP_FILE
          sudo fallocate -l 16G /mnt/swap_filex
          sudo chmod 600 /mnt/swap_filex
          sudo mkswap /mnt/swap_filex
          sudo swapon /mnt/swap_filex
          df -h
          free -h

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git libelf-dev dwarves
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /bin/repo

      - name: Set Environment Variable
        run: |
          echo "BUILD_TIME=$(date "+%y%m%d%H")" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=7a72" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=action" >> $GITHUB_ENV
          
          sudo mkdir -p /mnt/kernel_workspace
          sudo chmod 0777 /mnt/kernel_workspace
          
          echo "TOOLCHAIN_DIR=/mnt/toolchain" >> $GITHUB_ENV
          
          git config --global user.email "${{ env.KBUILD_BUILD_USER }}@${{ env.KBUILD_BUILD_HOST }}"
          git config --global user.name "${{ env.KBUILD_BUILD_HOST }}"

      - name: Download the Pre-built Toolchain
        run: |
            sudo mkdir -p ${{ env.TOOLCHAIN_DIR }}
            sudo chmod 0777 ${{ env.TOOLCHAIN_DIR }}
            cd ${{ env.TOOLCHAIN_DIR }}
            wget -O - https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/20052113d2a5552cfff78ac7b21fd7953cc1c592/clang-r563880.tar.gz | tar -xzf -

      - name: Sync the Kernel Source Code
        run: |
          echo "Changing to directory: /mnt/kernel_workspace..."
          cd "/mnt/kernel_workspace"
          
          echo "Sync kernel source"
          git clone --depth=1 https://github.com/yaap/kernel_oneplus_sm8650-modules sm8650-modules
          git clone --depth=1 https://github.com/7a72/kernel_oneplus_waffle.git -b waffle common
          
          echo "Get kernel version"
          echo KVER=$(awk '/^(VERSION|PATCHLEVEL|SUBLEVEL) =/ {v[++i]=$3} END {print v[1]"."v[2]"."v[3]}' ./common/Makefile) >> $GITHUB_ENV
          echo "${{ env.KVER }}"
          
          cd common
          
          echo "Pre-modify"
          rm -rf ./android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i 's/check_defconfig//' build.config.gki || true
          # sed -i '$s|echo "\$res"|echo "-zsck"|' scripts/setlocalversion || true
          # sed -i 's/^#define LINUX_COMPILER.*$/#define LINUX_COMPILER\t\t"clang-r536225"/' scripts/mkcompile_h || true

      - name: Add KernelSU
        run: |
          echo "Changing to directory: /mnt/kernel_workspace..."
          cd "/mnt/kernel_workspace"
          
          echo "Adding KernelSU..."
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          cd ./KernelSU
          KSU_VERSION=$(expr $(git rev-list --count HEAD) "+" 30000)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild

      - name: Apply patches
        run: |
          echo "Changing to directory: /mnt/kernel_workspace..."
          cd "/mnt/kernel_workspace"
          
          cd ./common
          cp $GITHUB_WORKSPACE/patches/hide_lineage.patch .
          patch -p1 < hide_lineage.patch

      - name: Add Configuration Settings
        run: |
          echo "Changing to directory: /mnt/kernel_workspace/common..."
          cd "/mnt/kernel_workspace/common"

          echo "Adding configuration settings to defconfig..."
          KCONFIG=$(realpath ./arch/arm64/configs/vendor/zsck.config)
          # KCONFIG=$(realpath ./arch/arm64/configs/gki_defconfig)
          # echo "CONFIG_KSU_MANUAL_HOOK=y" >> ${KCONFIG}

      - name: Build the Kernel
        run: |
          echo "Changing to configuration directory: /mnt/kernel_workspace/common..."
          cd "/mnt/kernel_workspace/common"
          
          # echo "Clean dirty"
          # git add -A
          # git commit -s -a -m "build"
          
          export PATH=${{ env.TOOLCHAIN_DIR }}/bin:$PATH
          
          echo "Building the kernel..."
          
          kargs="ARCH=arm64 LLVM=1 LLVM_IAS=1 -j$(nproc --all) O=out KBUILD_BUILD_HOST=${{ env.KBUILD_BUILD_HOST }} KBUILD_BUILD_USER=${{ env.KBUILD_BUILD_USER }}"
          make CC="clang" $kargs gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config vendor/zsck.config # Build the kernel config
          make CC="clang" $kargs # Build the kernel itself
          
          # make $kargs modules_install INSTALL_MOD_PATH=/mnt/kernel_workspace/Kernel_Prebuilts # Save the kernel modules
          # make $kargs install INSTALL_PATH=/mnt/kernel_workspace/Kernel_Prebuilts # Save the kernel image(s) and devicetrees
          # make $kargs headers_install INSTALL_HDR_PATH=/mnt/kernel_workspace/Kernel_Prebuilts/usr # Save the kernel headers

      # - name: Upload Kernel_Prebuilts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Kernel_Prebuilts
      #     path: /mnt/kernel_workspace/Kernel_Prebuilts/*

      - name: Create AnyKernel3
        run: |
          echo "Changing to configuration directory: /mnt/kernel_workspace/..."
          cd "/mnt/kernel_workspace/"
          
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          
          echo "Copying Image"
          cp /mnt/kernel_workspace/common/out/arch/arm64/boot/Image ./AnyKernel3/Image

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AK3-OP12-yaap-${{ env.KVER }}-${{ env.KSUVER }}_${{ env.BUILD_TIME }}
          path: /mnt/kernel_workspace/AnyKernel3/*
          
